name: Go Lint

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '**.go'

  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Lint Go code
        run: |
          go fmt ./...
          golint ./...
